services:
  - type: web
    name: rydex-socket-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        sync: false
      - key: NEXT_BASE_URL
        sync: false
